"""D75's backfill: one township, materialised then classified, with provenance on every row.

Run inside the stack, with the model service up (it is behind a compose profile):

    docker compose --profile model up -d ollama
    docker compose exec api python -m upto.classify.run 63000010

Two passes, in this order and for a reason:

1. **Materialise (D76).** Every `reference_place` in the township that has no `place` row
   gets one — origin `reference`, the 登錄字號 and nothing else, which is D28's shape. The
   category then has one home, 0007's own columns.
2. **Classify.** Every place in that township not yet decided is sent to the model one at a
   time — asked about **the best name this project holds** (D80: storefront sign → single
   brand → registered name), validated against D38's ten values, and written **with the
   prompt version, the model name and the asked string** (D39's condition 3, plus 0015's
   `category_input`). A legal-entity verdict is written as a **decided absence** (D79):
   provenance present, category NULL, so the next pass skips it — the measured cost this
   replaces was ~1,060 re-asks, an hour of inference per re-run. An answer outside the
   list is still not written and not coerced — a refusal is not a decision.

**The model's absence is ordinary, not an error.** The service is off unless a backfill is
running, so this exits 3 and says so, having written nothing. Exit 0 means the pass ran —
including the pass that had nothing left to do.

**Committed in batches rather than at the end**, because 3,324 places is roughly seven hours
and a crash at hour six must not throw away hour one. Each batch is a transaction; a
re-run resumes at the first unclassified row, which is what makes this safe to interrupt.
"""

from __future__ import annotations

import asyncio
import sys
from datetime import datetime, timezone

from sqlalchemy import text

from upto.api_common import SINGLE_BRAND, STOREFRONT
from upto.classify.classify import Classified, NoSignal, classify_name
from upto.classify.model import MODEL, available, ask
from upto.classify.prompt import PROMPT_VERSION
from upto.db import dispose_all, session_factory

BATCH = 25


async def clear_superseded(session, township_code: str) -> int:
    """Rows generated by an older prompt are cleared so this pass re-does them.

    D39 says two prompt versions are compared by re-running rather than by trusting either;
    a column holding both answers a different question per row, which is the shape this
    project refuses everywhere else. The provenance goes with the value — all four columns
    or none, which 0007's CHECK enforces anyway.
    """
    cleared = (
        await session.execute(
            text(
                "update place p set category = null, category_model = null, "
                "category_prompt_version = null, category_generated_at = null, "
                "category_input = null "
                "from reference_place rp "
                "where rp.registry_no = p.registry_no and rp.township_code = :tc "
                "and p.category_prompt_version is not null "
                "and p.category_prompt_version <> :v returning p.id"
            ),
            {"tc": township_code, "v": PROMPT_VERSION},
        )
    ).scalars().all()
    await session.commit()
    return len(cleared)


async def materialise(session, township_code: str) -> int:
    """D76: give the township's reference places their rows. Idempotent by 0007's index."""
    created = (
        await session.execute(
            text(
                "insert into place (origin, registry_no) "
                "select 'reference', rp.registry_no from reference_place rp "
                "where rp.publication_id = ("
                "  select id from place_publication order by detected_at desc limit 1"
                ") and rp.township_code = :tc "
                "and not exists ("
                "  select 1 from place p where p.origin = 'reference' "
                "  and p.registry_no = rp.registry_no"
                ") returning id"
            ),
            {"tc": township_code},
        )
    ).scalars().all()
    await session.commit()
    return len(created)


async def pending(session, township_code: str) -> list[tuple[int, str]]:
    """Places in this township not yet decided, each under the best name this project holds.

    **Undecided is `category_generated_at is null`, not `category is null`** — D79's decided
    absence carries provenance and no category, and re-asking it every pass is the measured
    hour this distinction exists to stop.

    **The name is D80's ladder: storefront sign → single brand → registered name** — the
    same precedence the screens read, because 悠旅生活事業股份有限公司 asked as itself is a
    legal entity, and asked as STARBUCKS COFFEE is a place with a category. The asked string
    goes into `category_input`, because the ladder's answer drifts as publications update
    and a stored verdict must say what it was a verdict about.
    """
    rows = (
        await session.execute(
            text(
                "select p.id, coalesce(storefront.name, brand.brand_name, rp.name) as name "
                "from place p "
                "join reference_place rp on rp.registry_no = p.registry_no "
                "left join lateral ("
                + STOREFRONT.format(registry="p.registry_no")
                + ") storefront on true "
                "left join lateral (" + SINGLE_BRAND.format(company="rp.name") + ") brand on true "
                "where p.origin = 'reference' and p.category_generated_at is null "
                "and rp.township_code = :tc "
                "and rp.publication_id = ("
                "  select id from place_publication order by detected_at desc limit 1"
                ") order by p.id"
            ),
            {"tc": township_code},
        )
    ).all()
    return [(row.id, row.name) for row in rows]


async def main(township_code: str) -> int:
    Session = session_factory()
    try:
        if not available():
            print(
                f"model {MODEL} is not reachable — the service is behind a compose profile "
                "and is off unless a backfill is running. Nothing was written.",
                file=sys.stderr,
            )
            return 3

        async with Session() as session:
            created = await materialise(session, township_code)
            cleared = await clear_superseded(session, township_code)
            todo = await pending(session, township_code)
        print(
            f"township {township_code}: {created} rows created, {cleared} cleared from an "
            f"older prompt, {len(todo)} to classify with {PROMPT_VERSION}"
        )

        done = no_signal = refused = 0
        for start in range(0, len(todo), BATCH):
            batch = todo[start : start + BATCH]
            results = []
            for place_id, name in batch:
                outcome = classify_name(name, ask)
                if isinstance(outcome, Classified):
                    results.append((place_id, name, outcome.category, outcome.prompt_version))
                elif isinstance(outcome, NoSignal):
                    # A legal entity, not a place. D79: written as a decided absence —
                    # provenance and the asked string, category NULL — so the next pass
                    # skips it instead of paying for this answer again. Counted apart from
                    # a refusal because they mean opposite things.
                    results.append((place_id, name, None, outcome.prompt_version))
                    no_signal += 1
                else:
                    refused += 1
            async with Session() as session:
                for place_id, asked, category, version in results:
                    await session.execute(
                        text(
                            "update place set category = :c, category_model = :m, "
                            "category_prompt_version = :v, category_generated_at = :t, "
                            "category_input = :i where id = :id"
                        ),
                        {
                            "c": category,
                            "m": MODEL,
                            "v": version,
                            "t": datetime.now(timezone.utc),
                            "i": asked,
                            "id": place_id,
                        },
                    )
                await session.commit()
            done += sum(1 for r in results if r[2] is not None)
            seen = done + no_signal + refused
            print(
                f"  {seen}/{len(todo)}  written {done}  legal-entity {no_signal}  "
                f"unusable {refused}",
                flush=True,
            )

        print(
            f"done: {done} classified, {no_signal} decided legal entities (recorded, not "
            f"re-asked), {refused} unusable answers left pending"
        )
        return 0
    finally:
        await dispose_all()


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python -m upto.classify.run <township_code>", file=sys.stderr)
        raise SystemExit(2)
    raise SystemExit(asyncio.run(main(sys.argv[1])))
