"""Item 10's two ingest tables, and the publication rows they hang off.

Revision ID: 0001
Created: 2026-08-11

Hand-written, not autogenerated. H10: autogenerated migrations drop the constraints the
database was chosen for, and every constraint below is the reason PostgreSQL was chosen —
the channel rule has to survive a writer that is not the application (D5).

Shape, and where each part comes from:

  * Forecast and observation are **two tables behind one read path** (D23), so there are two
    publication tables rather than one with a discriminator column.
  * A publication is identified by its **content hash** (D35, extended to the forecast by
    D42). The unique constraint on that hash is what makes an hourly fetch cheap: about
    twenty of twenty-four daily forecast runs publish nothing, and they must be silent
    successes rather than twenty-four rows for four facts.
  * `detected_at` is a **detection** time, not a publication time (D42). CWA's forecast
    carries no publication timestamp, so this column may never be presented as one — item
    14's lineage label has to be worded as detection.
  * Every timestamp is `timestamptz` (H17). A reading whose zone is unknown cannot be
    compared with a meal hour, which is the only thing these rows exist to answer.
"""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "forecast_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("dataset_id", sa.Text, nullable=False),
        # D19 names the dataset; the hash names the publication (D35, D42).
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        sa.UniqueConstraint("dataset_id", "content_sha256", name="uq_forecast_publication_content"),
        sa.CheckConstraint("payload_bytes > 0", name="ck_forecast_publication_nonempty"),
    )
    op.create_index("ix_forecast_publication_detected", "forecast_publication", ["detected_at"])

    op.create_table(
        "forecast_reading",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        # Township-level forecast (D19, D26): the township is how a place finds its forecast.
        sa.Column("township", sa.Text, nullable=False),
        sa.Column("element", sa.Text, nullable=False),
        sa.Column("slot_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("slot_end", sa.DateTime(timezone=True), nullable=True),
        # `element` is CWA's own name for the group (溫度, 舒適度指數); `measure` is the
        # named value inside it (Temperature, ComfortIndexDescription). One group carries
        # several measures, so both are needed to identify a reading — and calling the
        # second one `unit` would be a name that lies, since it holds no unit.
        sa.Column("measure", sa.Text, nullable=False),
        sa.Column("value", sa.Text, nullable=False),
        sa.ForeignKeyConstraint(["publication_id"], ["forecast_publication.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("publication_id", "township", "element", "measure", "slot_start"),
    )
    # The read path asks for one township, one element, one hour (D36), so that is the index.
    op.create_index(
        "ix_forecast_reading_lookup",
        "forecast_reading",
        ["township", "element", "measure", "slot_start"],
    )

    op.create_table(
        "observation_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        sa.Column("dataset_id", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        sa.UniqueConstraint("dataset_id", "content_sha256", name="uq_observation_publication_content"),
        sa.CheckConstraint("payload_bytes > 0", name="ck_observation_publication_nonempty"),
    )
    op.create_index("ix_observation_publication_detected", "observation_publication", ["detected_at"])

    op.create_table(
        "observation_reading",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        # A station reading, and the station id is the join key D26 resolves a township to.
        sa.Column("station_id", sa.Text, nullable=False),
        sa.Column("station_name", sa.Text, nullable=False),
        sa.Column("county", sa.Text, nullable=True),
        sa.Column("town", sa.Text, nullable=True),
        # The hour the reading describes. Distinct from detected_at: the observation carries
        # its own ObsTime, and that is the one the meal hour is compared against (D36).
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("element", sa.Text, nullable=False),
        # Nullable on purpose: the `Weather` text is absent in some publications, and how
        # often and why is still an open measurement question. A row that records the
        # absence is the only way that question stays answerable.
        sa.Column("value", sa.Text, nullable=True),
        sa.ForeignKeyConstraint(["publication_id"], ["observation_publication.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("publication_id", "station_id", "element", "observed_at"),
    )
    op.create_index(
        "ix_observation_reading_lookup",
        "observation_reading",
        ["station_id", "element", "observed_at"],
    )


def downgrade() -> None:
    op.drop_table("observation_reading")
    op.drop_table("observation_publication")
    op.drop_table("forecast_reading")
    op.drop_table("forecast_publication")
