"""Item 11's reference places, and the publication rows they hang off.

Revision ID: 0003
Revises: 0002
Created: 2026-08-11

Hand-written, not autogenerated (H10). Every constraint below is a claim this ingest makes
and would otherwise only make in a comment.

Shape, and where each part comes from:

  * A publication is identified by the **hash of the fetched archive** (D35). The archive's
    own stamp sits beside it as a label item 14 can show — **identity is the hash, the label
    is the stamp**, and when the two disagree the run says so rather than the schema deciding
    which one won.
  * A row inside a publication is pinned by D31's `食品業者登錄字號`, which is site-level and
    unique — measured again on 2026-08-11 as **827,784 distinct values in 827,784 rows**, so
    unique across the whole file rather than only within `餐飲場所`. The primary key is
    therefore `(publication_id, registry_no)`, which is D35's
    `(source, publication hash, 食品業者登錄字號)` with the publication row standing in for
    its first two parts. **That key is what makes a re-run harmless** (H14): the second write
    of an unchanged file collides instead of appending a second 36,499-row snapshot.
  * The township is a **foreign key, read out of the address** (D27), and it is nullable
    because an address that names no district costs its row a weather nudge and nothing else
    (D28). A null here is reported by the run and is re-derivable from the table afterwards —
    `where township_code is null` — which is why there is no second table of rejects.
  * `origin` is `reference` (D28, D30). Constant on this table, and stated anyway: a row read
    on its own has to answer where it came from without the reader knowing which table it was
    read out of, and D28 warns that the second migration is where that gets flattened.
  * Every timestamp is `timestamptz` (H17).

**Why the table is `reference_place` and not `place`.** D28's place is durable — credit and
provenance accumulate against one row across rounds — and these rows are not: a new
publication writes a fresh full set, so a row's identity here changes every time the source
republishes. They cannot be the same table without destroying D28's identity. Schema 5's
`place` table is unwritten, and when it arrives its `reference` rows will be fed *from* here
rather than being these rows.
"""

from alembic import op
import sqlalchemy as sa

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "place_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # `fda-97` — the publisher's dataset number. It names the file, not the slice kept
        # from it, because the hash covers the whole archive.
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        # The label, and it is nullable on purpose: a zip whose entry carries the 1980 epoch
        # has no stamp, and storing that as a date would put a false publication time on the
        # one screen item 14 exists to be honest on.
        sa.Column("archive_stamp", sa.DateTime(timezone=True), nullable=True),
        # When *we* saw it. Distinct from the stamp, and it is the only one of the two this
        # project produces.
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        sa.Column("entry_name", sa.Text, nullable=False),
        sa.Column("entry_bytes", sa.BigInteger, nullable=False),
        # What the rows under this publication cover — `餐飲場所 / 臺北市`. The archive holds
        # four categories nationwide, so a reader counting 36,499 rows under a 99 MB file
        # otherwise has no way to tell a filter from a truncated load.
        sa.Column("scope", sa.Text, nullable=False),
        # Filled by the same transaction that writes the places, so a committed publication
        # always carries them. Nullable rather than defaulted to zero: zero is a number and
        # would claim a parse produced nothing, where null says no parse is recorded.
        sa.Column("place_rows", sa.Integer, nullable=True),
        sa.Column("unresolved_township_rows", sa.Integer, nullable=True),
        # The identity constraint, and the whole of H14 for this ingest. D34 raised the number
        # of fetches from one a month to thirty, so the short-circuit has to hold thirty times
        # instead of once — and this is what holds when it does not.
        sa.UniqueConstraint("source", "content_sha256", name="uq_place_publication_content"),
        sa.CheckConstraint("payload_bytes > 0", name="ck_place_publication_nonempty"),
        sa.CheckConstraint("entry_bytes > 0", name="ck_place_publication_entry_nonempty"),
        sa.CheckConstraint(
            "unresolved_township_rows is null or place_rows is null "
            "or unresolved_township_rows <= place_rows",
            name="ck_place_publication_unresolved_within_rows",
        ),
    )
    op.create_index("ix_place_publication_detected", "place_publication", ["detected_at"])
    # The stamp is queried when a run asks "did the stamp move?" — the disagreement check D34
    # asked for reads the latest publication by detection time and compares this column.
    op.create_index("ix_place_publication_stamp", "place_publication", ["source", "archive_stamp"])

    op.create_table(
        "reference_place",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        # 食品業者登錄字號 — site-level and unique (D31), which is why no key had to be
        # invented for these rows.
        sa.Column("registry_no", sa.Text, nullable=False),
        sa.Column("origin", sa.Text, nullable=False),
        # Normalised for matching, raw kept beside it (H24). Storing only the normalised form
        # would make a suspected mis-normalisation un-investigable without re-fetching 17 MB;
        # storing only the raw form is the join that silently drops 36,488 of 36,499 rows.
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("name_raw", sa.Text, nullable=False),
        sa.Column("address", sa.Text, nullable=False),
        sa.Column("address_raw", sa.Text, nullable=False),
        # 統編 stays text: some begin with 0 (D31), and it identifies a company rather than a
        # site — the join on it was probed dead, so this column is provenance, not a key.
        sa.Column("business_no", sa.Text, nullable=True),
        # D27's geocode. Nullable, and a null is a reported outcome rather than a silent one.
        sa.Column("township_code", sa.Text, nullable=True),
        sa.Column("township_name", sa.Text, nullable=True),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["place_publication.id"], ondelete="CASCADE"
        ),
        # The reference table the township resolves against is ticket 06's, which holds the
        # twelve 臺北市 townships and their 內政部 codes. **Admitted cost: it is the weather
        # seed's table**, so a place row now depends on a table built for the station lookup.
        # D27's own cost list already names the alternative — a 內政部 鄉鎮市區代碼 table
        # seeded in its own right — and that becomes the correct answer the moment this ingest
        # stores a row outside 臺北市, because the twelve codes are all this table has.
        sa.ForeignKeyConstraint(
            ["township_code"], ["township_station.township_code"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("publication_id", "registry_no"),
        # Constant on this table and constrained to say so. D28's other two origins are other
        # rows in other tables; the column exists so this row answers for itself.
        sa.CheckConstraint("origin = 'reference'", name="ck_reference_place_origin"),
        # The code and the name move together, so a name with no code cannot sit here looking
        # like a resolved township.
        sa.CheckConstraint(
            "(township_code is null) = (township_name is null)",
            name="ck_reference_place_township_pair",
        ),
    )
    # The propose screen is a typeahead over this table (D28), and it searches the normalised
    # name. A btree serves exact and prefix matching; a substring search would want pg_trgm,
    # which is not installed and is not this ticket's to add.
    op.create_index("ix_reference_place_name", "reference_place", ["name"])
    # The read path asks for the places in one township of one publication (D26, D36).
    op.create_index(
        "ix_reference_place_township", "reference_place", ["township_code", "publication_id"]
    )


def downgrade() -> None:
    op.drop_table("reference_place")
    op.drop_table("place_publication")
