"""The brand source's own tables, and its foreign key on the run ledger.

Revision ID: 0013
Revises: 0012
Created: 2026-08-14

Hand-written, not autogenerated (H10). Ruled 2026-08-14: 臺北市食材登錄平台 is adopted as a
second reference source, and it gets **its own tables rather than columns on the FDA ones**,
because a row must answer "who said this" with one source. The FDA row says what the
registry calls the operator; this table says what the operator calls the shop.

Shape, and where each part comes from:

  * A publication is identified by the **hash of the fetched CSV** (D35's rule, applied to a
    source with no archive stamp at all — the download is a bare CSV, so the hash is the only
    version signal and there is no stamp column to disagree with it).
  * A row is one `(company_name, brand_name)` pair. The file itself is product-level (~29k
    rows of nutrition facts); the pairs are what this project keeps, deduplicated at parse.
    The primary key states that: one pair, once, per publication.
  * `company_name` is stored **normalised with the same function as `reference_place.name`**,
    because the whole point of the column is an exact-string join against it (probed
    2026-08-14: 188 of 266 companies join, 4,456 FDA rows citywide, 334 in 松山區). Raw kept
    beside it (H24).
  * **This migration does not decide the multi-brand rule.** 15 of 266 companies carry more
    than one brand; whether an ambiguous company gets patched is the read path's decision,
    and the table stores every pair so that decision stays revisable without re-ingesting.

`ingest_run` gains this source's foreign key, which is D24's pattern: one nullable key per
source, refused rather than defaulted for an unregistered one (see `runlog.py`). The two
CHECKs that count publications are rebuilt to count four columns instead of three.
"""

from alembic import op
import sqlalchemy as sa

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None

ONE_PUBLICATION = (
    "num_nonnulls(forecast_publication_id, observation_publication_id, "
    "place_publication_id{brand}) <= 1"
)
STORED_HAS_PUBLICATION = (
    "(outcome = 'stored') = (num_nonnulls(forecast_publication_id, "
    "observation_publication_id, place_publication_id{brand}) = 1)"
)


def upgrade() -> None:
    op.create_table(
        "brand_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # `taipei-foodtracer` — the platform, 臺北市食材登錄平台. Like `fda-97` it names the
        # file fetched, not the slice kept: the hash covers every product row, and what is
        # kept from it is recorded as scope.
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        # When *we* saw it. There is no archive stamp beside it because the source serves a
        # bare CSV: no zip entry, no Last-Modified worth trusting. The absence is the fact.
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        # `公司名稱→品牌名稱 / 臺北市` — the pairs, out of a product-level file.
        sa.Column("scope", sa.Text, nullable=False),
        # Filled by the same transaction that writes the pairs. Nullable rather than zero:
        # zero would claim a parse produced nothing, null says no parse is recorded.
        sa.Column("pair_rows", sa.Integer, nullable=True),
        sa.UniqueConstraint("source", "content_sha256", name="uq_brand_publication_content"),
        sa.CheckConstraint("payload_bytes > 0", name="ck_brand_publication_nonempty"),
    )
    op.create_index("ix_brand_publication_detected", "brand_publication", ["detected_at"])

    op.create_table(
        "brand_registration",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        # Normalised with `fda.normalise`, raw beside it (H24). The normalised form exists to
        # equal `reference_place.name`; the raw form is what the platform published.
        sa.Column("company_name", sa.Text, nullable=False),
        sa.Column("company_name_raw", sa.Text, nullable=False),
        sa.Column("brand_name", sa.Text, nullable=False),
        sa.Column("brand_name_raw", sa.Text, nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["brand_publication.id"], ondelete="CASCADE"
        ),
        # One pair, once. The file repeats each pair per product; the dedup is the parse's
        # job and this key is what catches the parse failing at it.
        sa.PrimaryKeyConstraint("publication_id", "company_name", "brand_name"),
        sa.CheckConstraint("company_name <> ''", name="ck_brand_registration_company"),
        sa.CheckConstraint("brand_name <> ''", name="ck_brand_registration_brand"),
    )
    # The read path's join: company name in, brands out, within one publication.
    op.create_index(
        "ix_brand_registration_company", "brand_registration", ["publication_id", "company_name"]
    )
    # The typeahead also matches the brand text itself — 摩斯 has to find the row whose FDA
    # name is 安心食品服務股份有限公司, or the patch fixes the reveal and not the search.
    op.create_index(
        "ix_brand_registration_brand", "brand_registration", ["publication_id", "brand_name"]
    )

    op.add_column(
        "ingest_run", sa.Column("brand_publication_id", sa.BigInteger, nullable=True)
    )
    op.create_foreign_key(
        "fk_ingest_run_brand_publication",
        "ingest_run",
        "brand_publication",
        ["brand_publication_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication",
        "ingest_run",
        ONE_PUBLICATION.format(brand=", brand_publication_id"),
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(brand=", brand_publication_id"),
    )


def downgrade() -> None:
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication", "ingest_run", ONE_PUBLICATION.format(brand="")
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(brand=""),
    )
    op.drop_constraint("fk_ingest_run_brand_publication", "ingest_run", type_="foreignkey")
    op.drop_column("ingest_run", "brand_publication_id")
    op.drop_table("brand_registration")
    op.drop_table("brand_publication")
