"""The storefront source's own tables, and its foreign key on the run ledger.

Revision ID: 0014
Revises: 0013
Created: 2026-08-14

Hand-written, not autogenerated (H10). Ruled 2026-08-14: 臺北市's 餐飲衛生分級評核 list is
the third reference source — the only **site-level** name source. An inspector stood in the
shop and wrote down what the sign says, keyed by the same 食品業者登錄字號 the FDA rows are
keyed by. That key is why this table needs no name join at all: 1,686 rows, zero missing and
zero duplicated registry numbers, 1,379 joining the current FDA publication exactly
(measured 2026-08-14).

Shape:

  * The publication pattern is 0013's — bare CSV, no stamp, identity is the content hash
    (D35), one FK per source on `ingest_run` (D24), CHECKs rebuilt to count five.
  * A row is one site: `(publication_id, registry_no)` is the key, exactly as
    `reference_place` keys its rows. The name is normalised with `fda.normalise` for
    display consistency, raw beside it (H24) — but unlike 0013's company column it is
    **not a join key**; the registry number is.
  * `grade` (優/良) is kept because it is one column and the source's own point — nothing
    reads it yet, and D20 rules what a surface may do with it if one ever does.

Why site-level outranks 0013's company-level patch at read time (stated here, executed in
`api_common`): the brand join says what the *company* calls its shops; this row says what
*this shop's* sign says — it is the only source that can split a multi-brand company's
sites, which is exactly the ambiguity D77 refused to guess at.
"""

from alembic import op
import sqlalchemy as sa

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None

ONE_PUBLICATION = (
    "num_nonnulls(forecast_publication_id, observation_publication_id, "
    "place_publication_id, brand_publication_id{storefront}) <= 1"
)
STORED_HAS_PUBLICATION = (
    "(outcome = 'stored') = (num_nonnulls(forecast_publication_id, "
    "observation_publication_id, place_publication_id, brand_publication_id{storefront}) = 1)"
)


def upgrade() -> None:
    op.create_table(
        "storefront_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # `taipei-hygiene-grade` — the dataset, 臺北市通過餐飲衛生管理分級評核業者.
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        # `店名 / 臺北市` — the names, out of a grading list.
        sa.Column("scope", sa.Text, nullable=False),
        sa.Column("name_rows", sa.Integer, nullable=True),
        sa.UniqueConstraint(
            "source", "content_sha256", name="uq_storefront_publication_content"
        ),
        sa.CheckConstraint("payload_bytes > 0", name="ck_storefront_publication_nonempty"),
    )
    op.create_index(
        "ix_storefront_publication_detected", "storefront_publication", ["detected_at"]
    )

    op.create_table(
        "storefront_name",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        # The join key, site-level and unique in the source file (measured: 1,686 of 1,686).
        sa.Column("registry_no", sa.Text, nullable=False),
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("name_raw", sa.Text, nullable=False),
        # 優 or 良 today; stored as text because the scale is the publisher's to extend.
        sa.Column("grade", sa.Text, nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["storefront_publication.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("publication_id", "registry_no"),
        sa.CheckConstraint("name <> ''", name="ck_storefront_name_nonempty"),
    )
    # The typeahead matches the storefront text — 五花馬 has to find the row whose FDA name
    # is a franchisee's registered one.
    op.create_index("ix_storefront_name_name", "storefront_name", ["publication_id", "name"])

    op.add_column(
        "ingest_run", sa.Column("storefront_publication_id", sa.BigInteger, nullable=True)
    )
    op.create_foreign_key(
        "fk_ingest_run_storefront_publication",
        "ingest_run",
        "storefront_publication",
        ["storefront_publication_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication",
        "ingest_run",
        ONE_PUBLICATION.format(storefront=", storefront_publication_id"),
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(storefront=", storefront_publication_id"),
    )


def downgrade() -> None:
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication", "ingest_run", ONE_PUBLICATION.format(storefront="")
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(storefront=""),
    )
    op.drop_constraint(
        "fk_ingest_run_storefront_publication", "ingest_run", type_="foreignkey"
    )
    op.drop_column("ingest_run", "storefront_publication_id")
    op.drop_table("storefront_name")
    op.drop_table("storefront_publication")
