"""A decided absence is distinguishable from an unasked row, and the question is recorded.

Revision ID: 0015
Revises: 0014
Created: 2026-08-14

Hand-written, not autogenerated (H10). Ruled 2026-08-14 (D79/D80), after the cost was
measured rather than assumed: 松山區's backfill tail was ~1,060 legal entities re-asked on
every pass — an hour of inference per re-run producing nothing the database could keep,
because "asked, and the answer is no category" and "never asked" were both four NULLs.

Two changes, one concern — what a category row can say about how it came to be:

  * **The provenance CHECK gains a third state.** 0007's rule was all-four-or-none; the rule
    is now: the three provenance columns move together, and a category may exist only with
    them. That admits `category NULL + provenance present`, which reads: **the model was
    asked, under this prompt version, and decided this is not a place** — 法人, the sentinel
    outcome ruled 2026-08-14, stored with D58's absence intact. A refusal still writes
    nothing; refusal and decision mean opposite things (the ingest_run no_change/failed
    distinction, one table over). The three states, each answering for itself:

        category NULL,    provenance NULL    — never asked; the next pass asks
        category present, provenance present — classified
        category NULL,    provenance present — asked; a legal entity, no category exists

  * **`category_input` records the exact string the model was asked about.** D80 makes the
    runner ask the best-known name (storefront sign → single brand → registered name), so
    the asked string is no longer derivable from the row: the display name drifts as
    publications update, and a comparison across models (D63's evaluation, hosted baselines
    included) is meaningless without knowing what each was asked. Same rule as the other
    three: present exactly when the row was decided.
"""

from alembic import op
import sqlalchemy as sa

revision = "0015"
down_revision = "0014"
branch_labels = None
depends_on = None

DECIDED = (
    "((category_model is null) = (category_prompt_version is null) and "
    " (category_model is null) = (category_generated_at is null) and "
    " (category_model is null) = (category_input is null) and "
    " (category is null or category_model is not null))"
)

ALL_OR_NOTHING = (
    "(category is null and category_model is null and "
    " category_prompt_version is null and category_generated_at is null) or "
    "(category is not null and category_model is not null and "
    " category_prompt_version is not null and category_generated_at is not null)"
)


def upgrade() -> None:
    op.add_column("place", sa.Column("category_input", sa.Text, nullable=True))
    # Rows decided before this revision were asked under their registered name — that is
    # what the old runner read — so the asked string is reconstructed from the latest
    # publication before the CHECK demands it. Reconstructed, and said so here: if a newer
    # publication had renamed a row between its ask and this migration the value would be
    # the newer name, but one publication exists at the time of writing, so it is exact.
    op.execute(
        "update place p set category_input = coalesce(("
        "  select rp.name from reference_place rp"
        "  join place_publication pp on pp.id = rp.publication_id"
        "  where rp.registry_no = p.registry_no"
        "  order by pp.detected_at desc limit 1"
        "), p.name) "
        "where p.category_generated_at is not null and p.category_input is null"
    )
    op.drop_constraint("ck_place_category_provenance", "place", type_="check")
    op.create_check_constraint("ck_place_category_provenance", "place", DECIDED)


def downgrade() -> None:
    # The sentinel rows cannot survive the narrower rule: their provenance is erased, which
    # returns them to "never asked" — the exact indistinguishability this revision removed.
    op.execute(
        "update place set category_model = null, category_prompt_version = null, "
        "category_generated_at = null where category is null and category_model is not null"
    )
    op.drop_constraint("ck_place_category_provenance", "place", type_="check")
    op.drop_column("place", "category_input")
    op.create_check_constraint("ck_place_category_provenance", "place", ALL_OR_NOTHING)
