"""The registry-status source's own tables, and its foreign key on the run ledger.

Revision ID: 0016
Revises: 0015
Created: 2026-08-14

Hand-written, not autogenerated (H10). Ruled 2026-08-14 (D81): the 商業登記 restaurant
roster is the fourth reference source, and the only one kept for a **negative** signal —
which businesses are recorded as no longer operating. Measured before ruling: 93 of 松山區's
364 joinable rows (25.5%) are dead in the roster and still present in FDA's current file,
so the FDA file provably does not purge closed shops.

Shape, and the two measured facts that forced it:

  * **統編 is not unique in the roster** — 2,189 of 206,611 appear more than once, 1,714
    with *mixed* statuses, including reuse across genuinely different businesses (the same
    number carrying 元氣堂養生館 歇業 and 祿記商號 核准設立). So the primary key includes
    the name and the status, and the read rule must aggregate: **a number is dead only if
    it has an explicitly dead row and no 核准設立 row.** One live row anywhere keeps every
    join visible.
  * **The status domain is wider than the obvious five** — 申覆（辯）期, 列入廢止中 and a
    handful of empty strings exist. Statuses are stored verbatim (never normalised: ／ is
    part of the label, not a width accident) and the dead set is an explicit allowlist on
    the read side; an unrecognised status defaults to visible, because hiding on uncertainty
    is the wrong direction for a filter whose failure mode is a living shop nobody can find.

The publication pattern is 0013's; `ingest_run` gains its sixth foreign key (D24), and the
two counting CHECKs are rebuilt to count six.
"""

from alembic import op
import sqlalchemy as sa

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None

ONE_PUBLICATION = (
    "num_nonnulls(forecast_publication_id, observation_publication_id, "
    "place_publication_id, brand_publication_id, storefront_publication_id{biz}) <= 1"
)
STORED_HAS_PUBLICATION = (
    "(outcome = 'stored') = (num_nonnulls(forecast_publication_id, "
    "observation_publication_id, place_publication_id, brand_publication_id, "
    "storefront_publication_id{biz}) = 1)"
)


def upgrade() -> None:
    op.create_table(
        "business_status_publication",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # `gcis-restaurant-registry` — 商業登記(依營業項目別)-餐館業, 經濟部商業發展署.
        sa.Column("source", sa.Text, nullable=False),
        sa.Column("content_sha256", sa.CHAR(64), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload_bytes", sa.Integer, nullable=False),
        sa.Column("scope", sa.Text, nullable=False),
        sa.Column("status_rows", sa.Integer, nullable=True),
        sa.UniqueConstraint(
            "source", "content_sha256", name="uq_business_status_publication_content"
        ),
        sa.CheckConstraint("payload_bytes > 0", name="ck_business_status_publication_nonempty"),
    )
    op.create_index(
        "ix_business_status_publication_detected",
        "business_status_publication",
        ["detected_at"],
    )

    op.create_table(
        "business_status_row",
        sa.Column("publication_id", sa.BigInteger, nullable=False),
        sa.Column("business_no", sa.Text, nullable=False),
        # The registered name, raw and audit-only: this table joins on the 統編 and never
        # on a name. It is in the key because 統編 reuse is real (measured above) and two
        # businesses under one number must both survive the write.
        sa.Column("name_raw", sa.Text, nullable=False),
        sa.Column("status", sa.Text, nullable=False),
        sa.ForeignKeyConstraint(
            ["publication_id"], ["business_status_publication.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("publication_id", "business_no", "name_raw", "status"),
        sa.CheckConstraint("business_no <> ''", name="ck_business_status_row_no"),
    )
    # The read path's whole question: the rows of one number, within one publication.
    op.create_index(
        "ix_business_status_row_no", "business_status_row", ["publication_id", "business_no"]
    )

    op.add_column(
        "ingest_run", sa.Column("business_status_publication_id", sa.BigInteger, nullable=True)
    )
    op.create_foreign_key(
        "fk_ingest_run_business_status_publication",
        "ingest_run",
        "business_status_publication",
        ["business_status_publication_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication",
        "ingest_run",
        ONE_PUBLICATION.format(biz=", business_status_publication_id"),
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(biz=", business_status_publication_id"),
    )


def downgrade() -> None:
    op.drop_constraint("ck_ingest_run_one_publication", "ingest_run", type_="check")
    op.drop_constraint("ck_ingest_run_stored_has_publication", "ingest_run", type_="check")
    op.create_check_constraint(
        "ck_ingest_run_one_publication", "ingest_run", ONE_PUBLICATION.format(biz="")
    )
    op.create_check_constraint(
        "ck_ingest_run_stored_has_publication",
        "ingest_run",
        STORED_HAS_PUBLICATION.format(biz=""),
    )
    op.drop_constraint(
        "fk_ingest_run_business_status_publication", "ingest_run", type_="foreignkey"
    )
    op.drop_column("ingest_run", "business_status_publication_id")
    op.drop_table("business_status_row")
    op.drop_table("business_status_publication")
