"""The crib the classifier reads from: the frozen set, embedded, one row per distinct name.

Revision ID: 0018
Revises: 0017
Created: 2026-08-15

Hand-written, not autogenerated (H10). D88, 2026-08-15: the prompt experiment ran out of
room — v4's three hand-written rules measurably *lost* accuracy against v3 (qwen 51.0→50.0,
gemma 51.5→49.5 on the frozen set), so the next lever is not more instruction but examples,
retrieved per name. This table is where they live.

**It is a derived cache of `testset_v1.json` and nothing more.** Every row can be rebuilt
from the frozen set plus an embedding model; nothing here is a source of truth, and the
table is emptied and rewritten whole by one command. Which is why two provenance columns
are not optional:

  * **`embed_model`** — a vector only means something beside other vectors from the same
    model. Two models mixed in one table would order neighbours by nothing at all.
  * **`testset_sha256`** — D82 freezes the set against re-drawing, *not* against the owner's
    corrections. A label amended in the JSON leaves this cache holding the old one, and a
    round run against a stale crib would be a measurement of yesterday's labels. The round
    runner compares this digest against the file's before it asks anything.
  * **`labeled_by`** — an example is a teacher, and the frozen set's labels were drafted by
    a model rather than adjudicated by the owner (disclosed 2026-08-15). A crib that cannot
    say who wrote it cannot be audited when it turns out to have taught the wrong thing.

**`name` is UNIQUE, and the frozen set is not.** 200 rows carry 179 distinct names —
7 names repeat, 21 rows in total, and no repeat disagrees with itself about its label
(measured 2026-08-15). So the collapse is lossless, and it is the right shape anyway: a
crib is a set of distinct names, and offering the model 「薔薇廳：其他」 twice would weight
one example by how often the draw happened to hit it. UNIQUE also makes the leave-one-out
exclusion whole — excluding the asked name excludes every copy of it.

The extension is created here rather than in `db/init`, because a database that already
exists (this stack's, and every temporary one an integration test builds) never re-runs the
init scripts. `IF NOT EXISTS` makes it idempotent on both.
"""

from alembic import op
import sqlalchemy as sa

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None

# 1024 is bge-m3's output width, pinned in the column rather than left to the loader: a
# silently different embedding model is exactly the failure this table cannot detect on its
# own, and a dimension mismatch is the one half of it PostgreSQL can refuse for us.
DIMENSION = 1024


def upgrade() -> None:
    op.execute("create extension if not exists vector")

    op.create_table(
        "example_embedding",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # The asked string, exactly as the frozen set spells it — this is what a neighbour
        # search returns and what the prompt prints, so any normalisation here would show up
        # as a crib the owner never labelled.
        sa.Column("name", sa.Text, nullable=False),
        sa.Column("label", sa.Text, nullable=False),
        # **Who authored the label, and it is not the owner.** Disclosed 2026-08-15: the
        # frozen set's labels were drafted by Fable 5 and cross-checked against Gemini, never
        # hand-adjudicated — so every row loaded from `testset_v1.json` is stamped
        # `fable5+gemini`. The column exists because a crib *teaches*, and a wrong answer has
        # to be traceable to its teacher; a later case book written by a different model
        # carries its own value here and the two never merge into an anonymous pile.
        sa.Column("labeled_by", sa.Text, nullable=False),
        # A finer tag than D38's ten — 手搖飲 under 咖啡飲料, 早餐店 under 早餐. Owner-ruled
        # 2026-08-15: **the product's ten categories do not change.** Granularity that would
        # be a schema change out in the product is retrieval metadata in here, and this column
        # is the whole of where it lives. The frozen set carries none, so it is NULL today.
        sa.Column("subtype", sa.Text, nullable=True),
        # Carried for diagnosis only. The prompt never prints it: telling the model that an
        # example came from the 招牌 layer would teach the layer, and the layers are how the
        # score is read rather than something the classifier is supposed to know.
        sa.Column("layer", sa.Text, nullable=False),
        sa.Column("embed_model", sa.Text, nullable=False),
        sa.Column("testset_sha256", sa.CHAR(64), nullable=False),
        sa.Column(
            "loaded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.UniqueConstraint("name", name="uq_example_embedding_name"),
        sa.CheckConstraint("name <> ''", name="ck_example_embedding_name"),
    )
    # Added by hand rather than declared above, because SQLAlchemy has no `vector` type
    # without the pgvector Python package — and that package is not a dependency this project
    # is willing to take for one column, when the whole of what it buys is spelling a list of
    # floats as `'[...]'::vector`, which the loader does itself.
    op.execute(
        "alter table example_embedding add column embedding vector({}) not null".format(DIMENSION)
    )
    # No ANN index. 179 rows is a sequential scan measured in microseconds, and an ivfflat or
    # hnsw index is an *approximate* one — it would trade exactness for a speed nobody here
    # needs, and a crib that silently drops the true nearest neighbour is an experiment
    # measuring the index instead of retrieval.


def downgrade() -> None:
    op.drop_table("example_embedding")
    # **The extension deliberately stays.** Dropping it from here would take out any other
    # table's vector column with it — a revision that reaches outside its own scope to
    # destroy data it does not own. `create extension if not exists` above is idempotent, so
    # leaving it costs a re-upgrade nothing.
