"""One example store, several embedders side by side — keyed by `embed_model`.

Revision ID: 0019
Revises: 0018
Created: 2026-08-17

Hand-written, not autogenerated (H10). D88's amendment, owner-ruled 2026-08-17: the
embedding model becomes a measured variable rather than a pinned constant, and the matrix is
3 embedders × 3 generators. 0018 pinned `name` UNIQUE, which allows exactly one embedder's
copy of the frozen set to exist at a time — loading a second would have to destroy the first,
and the nine cells would then be nine sequential re-loads rather than one table.

**The key becomes `(embed_model, name)`.** One name is still one crib *within an embedder*,
which is what keeps the leave-one-out exclusion whole (0018's argument, unchanged): excluding
the asked name still removes every copy of it from the space being searched.

**A round retrieves only among rows of its own embedder, and the filter is not optional.**
Cosine distance between vectors from two different models is a well-formed number that means
nothing — the spaces are unrelated, so a mixed search would order neighbours by an accident
of two coordinate systems. `nearest` therefore takes an `embed_model` and puts it in the
WHERE clause; this constraint is the half that stops two loads from colliding, and that
filter is the half that stops one query from crossing between them.

**The column stays `vector(1024)`, and that is measured rather than assumed.** All three
candidates were asked for a vector on 2026-08-17 through `/api/embed` and all three returned
1024: `bge-m3`, `qwen3-embedding:0.6b`, `snowflake-arctic-embed2`. So the pinned width still
refuses a silently-different model, which is the one half of the mixing failure PostgreSQL
can catch on its own. A fourth candidate of another width is a migration to a dimensionless
`vector`, not a widening of this one — pgvector allows it, and the cost is losing exactly
that refusal, which is a trade to make when there is something to trade it for.

`testset_sha256` is now singular *per embedder* rather than across the table: each embedder's
rows are written whole in one transaction, and `stored_sha(embed_model)` reads the digest of
that embedder's rows alone.
"""

from alembic import op

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_constraint("uq_example_embedding_name", "example_embedding", type_="unique")
    op.create_unique_constraint(
        "uq_example_embedding_model_name", "example_embedding", ["embed_model", "name"]
    )


def downgrade() -> None:
    # Deliberately destructive, and it says so: the old key cannot be restored while more than
    # one embedder's rows are present, and there is no correct choice of which to keep. The
    # table is a derived cache of `testset_v1.json` (0018) and nothing else, so emptying it
    # costs one `python -m upto.classify.examples load` per embedder and no data at all.
    op.execute("delete from example_embedding")
    op.drop_constraint("uq_example_embedding_model_name", "example_embedding", type_="unique")
    op.create_unique_constraint("uq_example_embedding_name", "example_embedding", ["name"])
