"""H32 — `TRUNCATE … CASCADE` may not walk through the guards `DELETE` respects.

Revision ID: 0020
Revises: 0019
Created: 2026-08-18

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-18, on H32's finding.

**What H32 measured (M4, `test_ingest_replay.py`).** `DELETE FROM place_publication` is refused —
`ingest_run.place_publication_id` is `ON DELETE SET NULL` and `ck_ingest_run_stored_has_publication`
forbids a `stored` run without a publication, so the schema does its job. `TRUNCATE
place_publication` is refused too, being referenced by a foreign key. But **`TRUNCATE
place_publication CASCADE` was allowed, and it emptied `ingest_run` for every source at once**,
because all seven publication foreign keys live on that one table. On the weather side it was
worse: `TRUNCATE forecast_publication CASCADE` silently removed `weight_contribution` rows — the
rows D14 rules permanent — through the five-column composite key, where the same `DELETE` is
refused by `fk_contribution_forecast_reading`.

**Why a trigger and not a rule in a document.** H32's mitigation was operational — *never `TRUNCATE
… CASCADE` in this database* — and the failure it guards against is silent *and* total: the audit
trail meant to explain a rebuild is what the rebuild destroys, and nothing else in the schema can
reconstruct it. A rule in a markdown file does not survive an operator at 2 am.

**Measured before it was written** (a scratch database, built and dropped, 2026-08-18): a
`BEFORE TRUNCATE … FOR EACH STATEMENT` trigger on a *cascaded child* fires when the parent is
truncated with `CASCADE`, raises, and **aborts the whole statement** — the parent's rows survive
untouched. So the guard belongs on the tables that must never be emptied, and the cascade is
stopped from the far end rather than by forbidding the near one.

**Where it goes, and where it deliberately does not.** On `ingest_run` and `weight_contribution`
only. **Never on the `<source>_row` tables**, because `TRUNCATE <source>_row` is M4's own
legitimate replay — shape A, rows-only, publication kept — and a guard there would break the exact
operation M4 proved correct. A mitigation that breaks the thing it protects is a regression.

**What this does not claim.** A superuser can `ALTER TABLE … DISABLE TRIGGER`. This makes the
destruction impossible **by accident**, not impossible. That is the whole of the intent: the silent
and easy path is closed, the deliberate one stays open and now has to be typed out, which is what
`test_ingest_replay.py`'s shape B does to reach a from-scratch rebuild. H32's operational rule
stays written down for the case the trigger cannot cover.
"""

from alembic import op

revision = "0020"
down_revision = "0019"
branch_labels = None
depends_on = None

# One function, two triggers. The message names the table, says why it is guarded, and says how to
# get past it on purpose — an error that does not tell the reader what the legitimate route is
# gets solved with `DISABLE TRIGGER` and no thought at all.
GUARD_FUNCTION = """
create or replace function upto_refuse_truncate() returns trigger
language plpgsql as $$
begin
    raise exception
        'H32: % may not be truncated, and a TRUNCATE ... CASCADE that reaches it is refused whole',
        TG_TABLE_NAME
    using hint =
        'This table is the audit trail a rebuild is supposed to explain, or a row D14 rules '
        'permanent. A replay is rows-only: TRUNCATE the source''s <source>_row table and keep '
        'the publication. If you genuinely mean to empty this table, say so out loud: '
        'ALTER TABLE ' || TG_TABLE_NAME || ' DISABLE TRIGGER USER, then re-enable it.';
end $$;
"""

TABLES = (
    # ingest_run holds every source's ledger, and all seven publication FKs live on it — so one
    # cascade from any publication table empties the lineage for all of them.
    "ingest_run",
    # weight_contribution rows are D14's permanent ones: authorship is erased at close, the
    # contribution is not, and a cascade through forecast_reading's composite key removed them.
    "weight_contribution",
)


def upgrade() -> None:
    op.execute(GUARD_FUNCTION)
    for table in TABLES:
        op.execute(
            "create trigger upto_no_truncate before truncate on {} "
            "for each statement execute function upto_refuse_truncate()".format(table)
        )


def downgrade() -> None:
    for table in TABLES:
        op.execute("drop trigger if exists upto_no_truncate on {}".format(table))
    op.execute("drop function if exists upto_refuse_truncate()")
