"""D102 / M3 — every publication records the shape of the file it came from.

Revision ID: 0021
Revises: 0020
Created: 2026-08-18

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-18 as D102.

**The question.** A source can change the shape of its file without changing what it is about — a
renamed column, a new one, a reordering — and this pipeline would carry on. Some of those changes
are invisible, some silently empty a field, and until now nothing recorded enough to tell which
happened, or when. So each publication stores its source's own ordered field names and a hash of
that list.

**Two columns per publication table, not a table of its own.** A publication's shape is a property
of the publication in exactly the way `payload_bytes`, `entry_name` and `scope` already are, and
those live in the row — so answering *what shape was this file* costs no join at all. **Rejected:
one `publication_signature` table with D24's seven nullable foreign keys**, the shape `ingest_run`
uses. It buys real foreign keys and one place to query, and it charges a join to read a property of
the row while growing its own FK list with every new source — the same widening cost as these
columns, plus a table. **Also rejected: one table keyed on `(source, content_sha256)` with no
foreign key.** Smallest, and the key is the publication's own identity by D18/D35, but the join is
unenforceable, which is precisely what D24 refuses and why `ingest_run` carries seven nullable
columns instead of a table name in text.

**Nothing is backfilled, and that is the ruling rather than laziness.** The raw file is not kept —
the publication tables hold the hash, the byte sizes, the entry name and row counts, never the
bytes — so a past publication's signature is recoverable only by re-fetching the source and finding
the content hash still matches. Measured 2026-08-18: that would reach **at most 7 of 210
publications**, and each of those seven gets a signature for free on its source's next publication.
The 41 forecast and 162 observation publications are unrecoverable at any price. So the columns are
nullable, `NULL` means *this publication predates the signature*, and the rows heal as the sources
republish — H33's rule, the third time it has decided something here.

**Deliberately not a CHECK.** A constraint requiring both columns together, or requiring them at
all, would refuse exactly the historical rows this migration is choosing to leave alone.
`upto.ingest.signature` is the one place that fills them, and `test_signature.py` is what holds the
hash rule still.
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0021"
down_revision = "0020"
branch_labels = None
depends_on = None

# The seven publication tables — the whole set, so a reader cannot wonder which were skipped.
TABLES = (
    "forecast_publication",
    "observation_publication",
    "place_publication",
    "brand_publication",
    "storefront_publication",
    "business_status_publication",
    "business_tax_publication",
)


def upgrade() -> None:
    for table in TABLES:
        op.add_column(
            table,
            # sha256 of the ordered names joined by U+001F. 64 hex characters, or absent.
            sa.Column("column_signature", sa.Text, nullable=True),
        )
        op.add_column(
            table,
            # The names themselves, so a drift report can say *which* column appeared or vanished
            # rather than only that the shape moved. A hash alone answers "did it change" and
            # nothing else, and the answer nobody can act on is the one that gets ignored.
            #
            # **`jsonb`, and the first version of this migration got it wrong.** `sa.JSON` maps to
            # PostgreSQL's `json`, which has **no ordering operator** — so `order by` every column
            # of the table raises `could not identify an ordering operator for type json`, and
            # that is exactly what M1's idempotency proof and M4's replay proof do to compare two
            # runs byte for byte. Both went red the moment these columns existed. `jsonb` orders,
            # indexes, and stores a canonical form; the array's element order is preserved (only
            # *object* keys are reordered, and this is an array), so nothing about the signature is
            # lost. **A column a measurement cannot sort is a column that silently narrows the
            # measurement** — M1 would have gone on passing while quietly not comparing these two.
            sa.Column("column_names", postgresql.JSONB, nullable=True),
        )


def downgrade() -> None:
    for table in TABLES:
        op.drop_column(table, "column_names")
        op.drop_column(table, "column_signature")
