"""A1 / item 4 — a preference is a member's own append-only row, and a round pins the version it read.

Revision ID: 0022
Revises: 0021
Created: 2026-08-18

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-18 (A1), with two points escalated
during the build and ruled separately — the uniqueness shape and `stance`, both recorded in D25.

**D17 gives this table its reason and D25 gives it its rule.** A preference is a person's *current
state* ("money is tight this month", "I avoid 燒烤"), which is a different fact from a contribution
— that is what happened in one round. It lives here because **re-confirmation happens outside a
round**: payday lands with no round open, and under the rejected alternative there would be nowhere
to put the update. **Nothing here is ever edited.** A change appends; the value *in force* varies
over time, the contents of a row never do, because D24 showed a mutable row can change underneath
a contribution that pinned it.

**No foreign key to `place`, and that is a decision rather than an omission.** A preference is
about a kind of food or a budget, never about a restaurant — 「避開麻辣」, not 「避開小林拉麵」.
Which places it touches is computed at fold time from the place's own category, so a preference
written in March keeps working on a restaurant added in May. A `place_id` here would freeze that,
and it would also make this table a list of restaurants a person dislikes, which is a much heavier
thing to hold than a category.

**No foreign key to `round` either, for D17's own reason:** a preference that needed a round to
hang from would have nowhere to go at the moment it is written. The round↔preference link lives on
the contribution, which is what `weight_contribution.preference_id` below is for — D24's pattern,
its sixth nullable key.

**`stance` exists because avoiding has to be reversible (ruled 2026-08-18).** Append-only with a
closed value list left no way to *stop* avoiding a category: there is no value meaning "not this",
nothing is edited and nothing is deleted, so a mis-tap would have been permanent. Un-avoiding now
appends `allow`; re-avoiding appends `avoid` again; the history reads as what actually happened.
`budget` has no stance and a CHECK says so, because a column that means two things for two kinds
is the shape D18/D24/D35 keep refusing. **Rejected:** deleting the row (destroys the version a
contribution pinned — D24's key would refuse it anyway, which is the database saying the same
thing); reusing `persist` (one column, two questions); an eleventh category value `none` (puts a
non-category into D38's closed list, and cannot express "stop avoiding 火鍋 but keep 燒烤").

**How "at most one row in force" is realised, since D25 describes a partial unique index over the
rows still in force and this migration does not create one.** "In force" is not directly
expressible without a supersession marker, and setting a marker on the older row is an *update* —
the one thing D25 forbids. So the identical guarantee is reached the other way: **unique on
`(member_id, valid_from)` per kind**, with the read path taking the latest. The latest row is
unique by construction, so at most one is in force; the index closes the only way that could break,
which is two rows landing at the same instant. Owner-accepted 2026-08-18 as the mechanism that
realises D25's sentence — **a later reader should not go looking for the partial index D25
describes, because it is deliberately not here.**

**The uniqueness is per kind, and that too was ruled.** D25's sentence — *at most one row in force
per member per kind* — was written with `budget` in mind, where one band in force is right. Carried
literally to `avoid_category` it would allow a member to avoid **exactly one** of D38's ten, and
avoiding both 麻辣 and 燒烤 is ordinary. So `budget` is unique per member, and `avoid_category` is
unique per member **per value** — a set, each element with its own version history.

**Nothing is backfilled and nothing needs to be**: this table starts empty, and
`weight_contribution.preference_id` is `NULL` on every existing row because no private
contribution has ever been written.
"""

from alembic import op
import sqlalchemy as sa

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None

# D38's ten, copied here because a CHECK cannot import. **The list is closed and validated in the
# database (D39's condition 2):** a value outside it is refused, never coerced — coercing 「拉麵」
# to 麵食 would turn a wrong answer into a plausible one, which is the H23 shape this schema keeps
# meeting. If D38's list ever changes, this constraint is part of the change.
CATEGORIES = ("麵食", "飯食", "小吃", "火鍋", "燒烤", "日式", "西式", "早餐", "咖啡飲料", "其他")

# §4C-2's two bands. Not a number: D38's *choices are picked from a fixed list, never typed* rule
# applies to a preference as much as to a proposal, and a typed budget would need a currency, a
# period and a model to read it.
BUDGET_BANDS = ("tight", "easy")

KINDS = ("budget", "avoid_category")


def _in(column: str, values) -> str:
    return "{} in ({})".format(column, ", ".join("'{}'".format(v) for v in values))


def upgrade() -> None:
    op.create_table(
        "preference",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # Member-scoped, never principal-scoped: D12 keeps `principal` holding nothing but an id,
        # and a preference is one of the facts that must not reach it (H19).
        sa.Column("member_id", sa.BigInteger, nullable=False),
        sa.Column("kind", sa.Text, nullable=False),
        sa.Column("value", sa.Text, nullable=False),
        # `avoid` | `allow` on a category, NULL on a budget. See the header.
        sa.Column("stance", sa.Text, nullable=True),
        # D17's opt-in, on the row rather than in a setting elsewhere: a `false` row is written,
        # used for the round in force, and erased on the schedule D14 established — so "do not
        # remember this" is a fact with provenance rather than an absence.
        sa.Column("persist", sa.Boolean, nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        # D25: salary is monthly, so a budget statement expires at the end of its month. Computed
        # at write time and stored, because a month boundary four readers each re-derive is how
        # two of them disagree. Taste has no expiry and giving it one would invent a number.
        sa.Column("expires_on", sa.Date, nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(["member_id"], ["member.id"], ondelete="CASCADE"),
        sa.CheckConstraint(_in("kind", KINDS), name="ck_preference_kind"),
        # The value's list depends on the kind, so one CHECK per kind rather than one loose list —
        # otherwise `kind='budget', value='火鍋'` would pass.
        sa.CheckConstraint(
            "(kind <> 'budget') or ({})".format(_in("value", BUDGET_BANDS)),
            name="ck_preference_budget_value",
        ),
        sa.CheckConstraint(
            "(kind <> 'avoid_category') or ({})".format(_in("value", CATEGORIES)),
            name="ck_preference_category_value",
        ),
        # A stance belongs to a category and to nothing else. Both directions, so neither a
        # budget with a stance nor a category without one can exist.
        sa.CheckConstraint(
            "(kind = 'avoid_category') = (stance is not null)",
            name="ck_preference_stance_only_on_category",
        ),
        sa.CheckConstraint(
            "stance is null or stance in ('avoid', 'allow')", name="ck_preference_stance_value"
        ),
        # D25's month, as a biconditional: a budget always expires, a taste never does.
        sa.CheckConstraint(
            "(kind = 'budget') = (expires_on is not null)", name="ck_preference_budget_expires"
        ),
    )

    # D25 names this one: the read path asks for a member's latest row of a kind, so the index is
    # the query.
    op.create_index(
        "ix_preference_in_force", "preference", ["member_id", "kind", sa.text("valid_from desc")]
    )

    # The two uniqueness rules, one per kind. Both are on `valid_from` rather than on a
    # supersession marker — see the header for why that is the same guarantee.
    op.create_index(
        "uq_preference_budget_version", "preference", ["member_id", "valid_from"],
        unique=True, postgresql_where=sa.text("kind = 'budget'"),
    )
    op.create_index(
        "uq_preference_category_version", "preference", ["member_id", "value", "valid_from"],
        unique=True, postgresql_where=sa.text("kind = 'avoid_category'"),
    )

    # D24's sixth nullable key: a round records not only the number a preference produced but
    # **which version of it was read**, which is what D25's retention rule leans on — a version a
    # contribution points at cannot be deleted, and the database refuses without anyone
    # remembering the rule.
    op.add_column(
        "weight_contribution", sa.Column("preference_id", sa.BigInteger, nullable=True)
    )
    op.create_foreign_key(
        "fk_contribution_preference", "weight_contribution", "preference",
        ["preference_id"], ["id"], ondelete="RESTRICT",
    )

    # **`ck_contribution_exactly_one_source` has to widen, and the integration test is what found
    # it.** The constraint read `num_nonnulls(forecast_publication_id, observation_publication_id)
    # = 1` — exactly one *weather* pin — so before this change **a preference contribution was
    # structurally impossible to store**: it pins neither reading, and the CHECK refused it. The
    # invariant worth keeping is "a contribution has exactly one source", not "a contribution is
    # about the weather", so the third key joins the count rather than the rule being relaxed.
    # Recorded here rather than only in a commit message because the next source (a coupon, D30's
    # partner) will meet the same constraint and should find the pattern already stated.
    op.drop_constraint("ck_contribution_exactly_one_source", "weight_contribution", type_="check")
    op.create_check_constraint(
        "ck_contribution_exactly_one_source", "weight_contribution",
        "num_nonnulls(forecast_publication_id, observation_publication_id, preference_id) = 1",
    )

    # D13's third column is *who may see the reason*, and `ck_contribution_commercial_public`
    # already forces the commercial case to be public. This is the mirror the private channel
    # needed: a private reason may be `represented_member` or `none`, and **never `table`** —
    # a preference on the reveal panel is the exposure §3.0 is built against, and at five people
    # a channel label is guessable enough without the sentence beside it.
    op.create_check_constraint(
        "ck_contribution_private_not_public", "weight_contribution",
        "channel <> 'private' or reason_visibility <> 'table'",
    )


def downgrade() -> None:
    op.drop_constraint("ck_contribution_private_not_public", "weight_contribution", type_="check")
    op.drop_constraint("ck_contribution_exactly_one_source", "weight_contribution", type_="check")
    op.create_check_constraint(
        "ck_contribution_exactly_one_source", "weight_contribution",
        "num_nonnulls(forecast_publication_id, observation_publication_id) = 1",
    )
    op.drop_constraint("fk_contribution_preference", "weight_contribution", type_="foreignkey")
    op.drop_column("weight_contribution", "preference_id")
    op.drop_index("uq_preference_category_version", table_name="preference")
    op.drop_index("uq_preference_budget_version", table_name="preference")
    op.drop_index("ix_preference_in_force", table_name="preference")
    op.drop_table("preference")
