"""A1 / D103 — a third kind of preference: 「不吃 X」, recorded as a choice and never as a condition.

Revision ID: 0023
Revises: 0022
Created: 2026-08-18

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-18 (D103 amended).

**This is the product's founding reason, and the reason it is shaped this way is the PDPA.** A
person who cannot eat peanuts has to be able to say so, and the app has to act on it. What it must
**not** do is record *why*. 「不吃花生」 is a preference; 「花生過敏」 is health information about an
identified person, and holding that would put a dinner app inside a regime built for medical
records. So the table stores an avoidance, the value list happens to be 衛福部's food-label
allergen groups because that is the list Taiwanese packaging already uses, and **no surface may
contain the word 過敏** — that rule belongs to the copy and is stated in D103 rather than here,
because a CHECK cannot enforce it and pretending otherwise would be worse than writing it down.

**Nothing about the mechanism is new, which is the point of adding it as a third `kind` rather than
a fourth table.** `stance` works exactly as it does for a category, so un-avoiding appends `allow`
and a mis-tap is reversible; uniqueness is per `(member_id, value)` for the same reason it is for a
category — a person may avoid 花生 and 甲殼類 both, so one row in force *per value* is the rule and
one row in force per kind would allow exactly one avoidance. **Rejected: a separate
`preference_ingredient` table** — it would duplicate `stance`, `persist`, the versioning and the
`weight_contribution` key for a row that differs only in which closed list its value comes from.

**Two things that differ from `avoid_category`, and both are deliberate.**

**It does not expire, and it is not inherited either.** D25's rule for a category stance is that it
stands until changed. B1's carry rule for *this* kind is narrower: **show, and require the tap even
for a stance.** A category stance is a taste, and a taste held last month is still yours this
month. An ingredient stance is a fact about a body, and the honest thing is to re-offer it and let
the person confirm rather than assume it silently. So `expires_on` stays NULL by CHECK — the row
does not lapse — and the *screen* asks again. Anyone tempted to make the two kinds' date handling
consistent should read this paragraph first: the inconsistency is the ruling.

**It is never applied by speak-for.** One person may roll on behalf of a circle, and they may not
carry someone else's ingredient avoidance into a round the absent person did not join. That is an
API rule rather than a schema one and lives in the loader; recorded here because the table is where
someone will come looking for it.

**The contributor does nothing today and that is stated rather than hidden.** No place carries
ingredient data — there is no source for it and none planned — so an ingredient avoidance is stored
and produces no contribution. `GET /circles/{id}/preferences` reports `ingredient_coverage`, which
is 0 today, for the same reason it reports `category_coverage`: a screen offering eleven choices
that change nothing must be able to say so, and the figure must never be written into markup.
"""

from alembic import op
import sqlalchemy as sa

revision = "0023"
down_revision = "0022"
branch_labels = None
depends_on = None

# 衛福部's eleven food-label allergen groups, as they appear on Taiwanese packaging. Copied here
# because a CHECK cannot import, exactly as 0022 copied D38's ten. **The list is closed and refused
# rather than coerced** — a value outside it is rejected, because coercing 「腰果」 to 堅果類 would
# turn a wrong answer into a plausible one, and here a plausible-but-wrong answer is one somebody
# eats.
INGREDIENTS = (
    "甲殼類", "芒果", "花生", "牛奶／羊奶", "蛋", "堅果類",
    "芝麻", "含麩質之穀物", "大豆", "魚類", "亞硫酸鹽類",
)

CATEGORIES = ("麵食", "飯食", "小吃", "火鍋", "燒烤", "日式", "西式", "早餐", "咖啡飲料", "其他")
BUDGET_BANDS = ("tight", "easy")
KINDS = ("budget", "avoid_category", "avoid_ingredient")
AVOIDANCES = ("avoid_category", "avoid_ingredient")


def _in(column: str, values) -> str:
    return "{} in ({})".format(column, ", ".join("'{}'".format(v) for v in values))


def upgrade() -> None:
    # The kind list widens. Dropped and recreated rather than added to, because a CHECK is a whole
    # expression and there is no ALTER for part of one.
    op.drop_constraint("ck_preference_kind", "preference", type_="check")
    op.create_check_constraint("ck_preference_kind", "preference", _in("kind", KINDS))

    op.create_check_constraint(
        "ck_preference_ingredient_value", "preference",
        "(kind <> 'avoid_ingredient') or ({})".format(_in("value", INGREDIENTS)),
    )

    # **The stance biconditional now covers both avoidances, and the constraint is renamed.** It was
    # `ck_preference_stance_only_on_category`, and leaving that name on a rule about two kinds would
    # be a comment that lies in the one place nobody edits — a constraint name shows up in the error
    # a client sees.
    op.drop_constraint("ck_preference_stance_only_on_category", "preference", type_="check")
    op.create_check_constraint(
        "ck_preference_stance_only_on_avoidance", "preference",
        "({}) = (stance is not null)".format(_in("kind", AVOIDANCES)),
    )

    # `ck_preference_budget_expires` is untouched: a budget still always expires and **an ingredient
    # avoidance still never does.** B1's re-confirmation for this kind is a screen behaviour, not a
    # lapse — see the header. Writing `expires_on` here would make the row disappear from "in force"
    # and silently switch an avoidance off, which is the opposite of asking again.

    # Uniqueness per value, the same shape as the category's and a separate partial index rather
    # than a widened one. Two kinds in one index would collide the day a value appeared in both
    # closed lists — none does today, and a schema that only works while two lists stay disjoint is
    # a schema waiting for a list to change.
    op.create_index(
        "uq_preference_ingredient_version", "preference", ["member_id", "value", "valid_from"],
        unique=True, postgresql_where=sa.text("kind = 'avoid_ingredient'"),
    )


def downgrade() -> None:
    # Rows of the new kind cannot survive a narrower CHECK, and they are the person's own statement
    # rather than derived data — so they are deleted explicitly here rather than left to make the
    # constraint fail. A downgrade that cannot say what it destroys should not run.
    op.execute("delete from preference where kind = 'avoid_ingredient'")
    op.drop_index("uq_preference_ingredient_version", table_name="preference")
    op.drop_constraint("ck_preference_stance_only_on_avoidance", "preference", type_="check")
    op.create_check_constraint(
        "ck_preference_stance_only_on_category", "preference",
        "(kind = 'avoid_category') = (stance is not null)",
    )
    op.drop_constraint("ck_preference_ingredient_value", "preference", type_="check")
    op.drop_constraint("ck_preference_kind", "preference", type_="check")
    op.create_check_constraint(
        "ck_preference_kind", "preference", _in("kind", ("budget", "avoid_category")),
    )
