"""B2 / item 9 — the trip is named; the proposal it came from never is.

Revision ID: 0024
Revises: 0023
Created: 2026-08-19

Hand-written, not autogenerated (H10). Shape owner-ruled 2026-08-18, ticket
`doc/issues/B2-post-meal-trip.md`.

**§3.0's asymmetry is the whole design, and this table is where it is realised.** A *proposal* is
anonymous — D14's trigger nulls `proposal.member_id` when a round closes, so after the fact nothing
records who put a place forward. A *trip* is named: somebody says "we went", and that is a fact about
a group outing rather than an opinion about a restaurant. **So this table carries a `member_id` and
keeps it**, and the two halves of §3.0 sit in the same database without contradiction because they
are about different acts.

**And the erasure must not be walked backwards.** The winner is derived from
`round.winning_place_id`, never copied here, so a trip cannot be joined to a proposal to recover an
author — D14 already removed the only column that could. A `place_id` here would be harmless in
itself and would make the join possible, so it is absent by decision. **Rejected:** a `place_id`
column "for convenience"; D28/D57's derive-at-read rule is the same argument.

**One trip per round, and it is a UNIQUE rather than an application check.** Two people tapping at
once must not produce two trips, and the second must be told who was first — which is D68's
409-with-the-fact idiom, and it needs the database to be the thing that decides. A `SELECT` then an
`INSERT` in the endpoint would race.

**The composite foreign keys are the point of this migration rather than a detail.** A trip must be
signed by a member **of the round's own circle**. Two plain keys — `member_id → member(id)` and
`round_id → round(id)` — would each be satisfied while the member belonged to a different circle
entirely, and the endpoint would be the only thing standing between a stranger and a signature. So
`circle_id` is stored and both keys carry it:

- `(circle_id, member_id) → member(circle_id, id)`
- `(circle_id, round_id) → round(circle_id, id)`

Neither parent had a unique index on that pair, so this revision adds both — `uq_member_circle_id`
and `uq_round_circle_id`. They are redundant against the primary keys in the ordinary sense and
**they are what makes the composite reference expressible at all**, which is a different job from
uniqueness.

**No note, and no free text of any kind (D38).** 「我們去了」 is the whole message; a note would be a
place for one person to characterise an evening five people had.

**One signature means who *signed*, not who went.** Attendance is a later `trip_attendee` table if it
is ever ruled — never a column here, because a list of who came is a different fact with a different
privacy weight, and squeezing it into this row would make one column answer two questions.
"""

from alembic import op
import sqlalchemy as sa

revision = "0024"
down_revision = "0023"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # The parent indexes the composite keys need. Added first, because a foreign key referencing
    # them cannot be created until they exist.
    op.create_index("uq_member_circle_id", "member", ["circle_id", "id"], unique=True)
    op.create_index("uq_round_circle_id", "round", ["circle_id", "id"], unique=True)

    op.create_table(
        "trip",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # UNIQUE, not merely indexed: one trip per round, decided by the database so two
        # simultaneous taps cannot both win. See the header.
        sa.Column("round_id", sa.BigInteger, nullable=False, unique=True),
        # Stored so both keys can carry it. It is derivable from the round, and storing it is what
        # lets the *database* refuse a signature from outside the circle instead of trusting code.
        sa.Column("circle_id", sa.BigInteger, nullable=False),
        # Kept, unlike `proposal.member_id`. §3.0: a proposal is anonymous, a trip is named.
        sa.Column("member_id", sa.BigInteger, nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(
            ["circle_id", "round_id"], ["round.circle_id", "round.id"],
            name="fk_trip_round_in_circle",
        ),
        sa.ForeignKeyConstraint(
            ["circle_id", "member_id"], ["member.circle_id", "member.id"],
            name="fk_trip_member_in_circle",
        ),
        # No `place_id`: the winner is read from `round.winning_place_id` (D28/D57). No `note`
        # column: D38 admits no free text. Both absences are decisions and both are in the header.
    )


def downgrade() -> None:
    op.drop_table("trip")
    op.drop_index("uq_round_circle_id", table_name="round")
    op.drop_index("uq_member_circle_id", table_name="member")
