"""D105 — the operator role lives on the credential, not on the person.

Revision ID: 0025
Revises: 0024
Created: 2026-08-19

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-18 (D105), on the backend session's
recommendation after both offered locations turned out to be closed by existing rules.

**Why not a column on `principal`.** D12 keeps `principal` holding nothing but an id and a stamp, and
`test_identity_integration.py` asserts exactly that. Beyond the test: a role there is a **cross-circle
fact about a human being**, readable from every circle they sit in, which is precisely the
correlation surface D12 and H19 exist to keep blank.

**Why not an `operator` table.** H19 permits a reference to `principal` only from a table that can
honestly call itself authentication — the check is an allowlist, and adding a name to it is how a
migration *declares* "this is authentication, not domain". **A role is authorisation.** Getting
through the allowlist by mislabelling would be visible in the diff and still wrong: it would turn a
guard into a formality.

**So it is a flag on `device_secret`,** which is already in that allowlist, already authentication,
and already the thing D74's CLI issues. Three consequences, and two of them are why this is the
better answer rather than merely the permitted one:

1. **The role is set at issue time and can never arrive as a parameter.** `upto.issue … --operator`
   writes it; no request can ask for it. The response shape is then chosen by *which credential
   authenticated* — one input, no flag — so H3's rule holds structurally rather than by validation.
2. **The role is revocable on its own.** Revoking the operator device leaves the person's seat
   intact. A principal-level flag could not be withdrawn without withdrawing the person, which is
   the wrong thing to have to do the first time a device is lost.
3. **It stops being a fact about a person and becomes a capability held by presenting a credential.**
   The same human is an ordinary member on their phone and an operator on the issued device. That is
   the honest description of what an operator view is, and it keeps `principal` empty.

**The cost, stated because it is real.** One principal may hold two secrets with different roles, so
"is this person an operator" has no single answer — it is per credential. Any screen wanting to say
"you are an operator" must read the authenticated secret rather than the person, and a reader
expecting a boolean on the human will find none.

**Default false, not null.** A secret issued before this revision, or by a caller that does not pass
the flag, is an ordinary member's — the safe direction, and the one that needs no backfill.
"""

from alembic import op
import sqlalchemy as sa

revision = "0025"
down_revision = "0024"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "device_secret",
        sa.Column("operator", sa.Boolean, nullable=False, server_default=sa.text("false")),
    )


def downgrade() -> None:
    # The flag is the only record that a secret was an operator's, so dropping the column revokes
    # every operator view. That is the honest consequence rather than a loss to work around: the
    # role has no home outside this column by design.
    op.drop_column("device_secret", "operator")
