"""D113 — an operator-authored alias that may match a search and may never be displayed.

Revision ID: 0028
Revises: 0027
Created: 2026-08-20

Hand-written, not autogenerated (H10). Owner-ruled 2026-08-20 as D113, from the evaluator's first
data-quality finding: `星巴克` returned nothing because **no publisher has ever written those three
characters**. The 176 branches are `悠旅生活事業股份有限公司`; the brand pairing is
`悠旅生活事業股份有限公司 → STARBUCKS COFFEE`, English only; the single `星巴克` string in the whole
database is one sign row whose registry_no has no place row in any publication.

**This is the first table here holding data no publisher stands behind, and every column exists to
keep that fact attached to it.**

**`search_alias`, not `place_alias`, and the name is load-bearing.** A table called `place_alias`
invites somebody to render one. D113's first iron law is *match-only, never displayed*: the alias
widens what a query can hit, and every name a member SEES still comes from a publisher through
D92's ladder. The name of the table is the first line of that defence; the second is that
`upto/live.py` puts it in a `where` clause and never in the `select` list.

**`authored_by` and `authored_at` are NOT NULL because they are the point** (D113's second iron
law). An alias error is *ours* and traceable to nobody else — that is the cost the owner accepted,
and a row that cannot say who wrote it and when has quietly become indistinguishable from source
data. `note` carries the verification: what in the *published* data makes this mapping believable.

**No foreign key, deliberately, and this is D113's «joins nothing else» bound.** `registered_name`
is text matched against `reference_place.name`. A foreign key would need a target, and the only
candidates are publication-scoped rows that come and go with every republication — so the key would
either break on the next publication or drag the alias into the publication lifecycle. It also
would not be *one* join: it would be the first of several, and the bound exists because this table
must stay a lookup and never become a participant.

**Deliberately not indexed.** The table is small by ruling — common foreign-branded chains, no
completeness claim — and it is read once per search with a sequential scan over single digits of
rows. An index here would be a claim about growth that the ruling does not make.

**What must never read this table:** the classifier, the RAG crib, and any derived name
(`upto/naming.py`, `upto/api_common.compose_names`). Asserted by
`app/api/tests/test_search_alias.py`, which walks the imports rather than trusting the rule.
"""

from alembic import op
import sqlalchemy as sa

revision = "0028"
down_revision = "0027"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "search_alias",
        sa.Column("id", sa.BigInteger, primary_key=True),
        # What a person actually types. `星巴克`.
        sa.Column("alias", sa.Text, nullable=False),
        # The publisher's registered name it stands for. `悠旅生活事業股份有限公司`.
        sa.Column("registered_name", sa.Text, nullable=False),
        # D113's second iron law, in two columns that cannot be omitted.
        sa.Column("authored_by", sa.Text, nullable=False),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=False),
        # What in the published data makes the mapping believable — the brand pairing, usually.
        # NOT NULL because an alias nobody can check is an alias nobody can withdraw.
        sa.Column("note", sa.Text, nullable=False),
        sa.UniqueConstraint("alias", "registered_name", name="uq_search_alias_pair"),
        sa.CheckConstraint("length(btrim(alias)) > 0", name="ck_search_alias_alias_nonempty"),
        sa.CheckConstraint(
            "length(btrim(registered_name)) > 0", name="ck_search_alias_registered_nonempty"
        ),
        sa.CheckConstraint("length(btrim(authored_by)) > 0", name="ck_search_alias_author_named"),
        sa.CheckConstraint("length(btrim(note)) > 0", name="ck_search_alias_note_given"),
    )


def downgrade() -> None:
    op.drop_table("search_alias")
